# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("extensions.enabledItems", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.1.9");
user_pref("extensions.lastAppVersion", "3.1.9");
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.accountmanager.accounts", "account1,account2");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.accountmanager.localfoldersserver", "server2");
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.identity.id1.draft_folder", "imap://pdo762@mail.it.northwestern.edu/Drafts");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "0");
user_pref("mail.identity.id1.fcc_folder", "imap://pdo762@mail.it.northwestern.edu/Sent");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "0");
user_pref("mail.identity.id1.fullName", "Pamela Dornan");
user_pref("mail.identity.id1.stationery_folder", "imap://pdo762@mail.it.northwestern.edu/Templates");
user_pref("mail.identity.id1.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id1.useremail", "p-dornan@northwestern.edu");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.rights.version", 1);
user_pref("mail.root.imap", "C:\\Documents and Settings\\pdo762\\Application Data\\Thunderbird\\Profiles\\uzhej7fp.default\\ImapMail");
user_pref("mail.root.imap-rel", "[ProfD]ImapMail");
user_pref("mail.root.none", "C:\\Documents and Settings\\pdo762\\Application Data\\Thunderbird\\Profiles\\uzhej7fp.default\\Mail");
user_pref("mail.root.none-rel", "[ProfD]Mail");
user_pref("mail.server.server1.authMethod", 0);
user_pref("mail.server.server1.check_new_mail", true);
user_pref("mail.server.server1.directory", "C:\\Documents and Settings\\pdo762\\Application Data\\Thunderbird\\Profiles\\uzhej7fp.default\\ImapMail\\mail.it.northwestern.edu");
user_pref("mail.server.server1.directory-rel", "[ProfD]ImapMail/mail.it.northwestern.edu");
user_pref("mail.server.server1.hostname", "mail.it.northwestern.edu");
user_pref("mail.server.server1.login_at_startup", true);
user_pref("mail.server.server1.name", "p-dornan@northwestern.edu");
user_pref("mail.server.server1.port", 993);
user_pref("mail.server.server1.socketType", 3);
user_pref("mail.server.server1.type", "imap");
user_pref("mail.server.server1.userName", "pdo762");
user_pref("mail.server.server2.directory", "C:\\Documents and Settings\\pdo762\\Application Data\\Thunderbird\\Profiles\\uzhej7fp.default\\Mail\\Local Folders");
user_pref("mail.server.server2.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server2.hostname", "Local Folders");
user_pref("mail.server.server2.name", "Local Folders");
user_pref("mail.server.server2.type", "none");
user_pref("mail.server.server2.userName", "nobody");
user_pref("mail.smtp.defaultserver", "smtp2");
user_pref("mail.smtpserver.smtp2.authMethod", 3);
user_pref("mail.smtpserver.smtp2.description", "NU Exchange Mail");
user_pref("mail.smtpserver.smtp2.hostname", "Mail.it.northwestern.edu");
user_pref("mail.smtpserver.smtp2.port", 587);
user_pref("mail.smtpserver.smtp2.try_ssl", 3);
user_pref("mail.smtpserver.smtp2.username", "pdo762");
user_pref("mail.smtpservers", "smtp2");
user_pref("mail.spam.version", 1);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "3.1.9");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
